CREATE TABLE [dbo].[ACESSOSCLIENTE] (
    [ID]                BIGINT   IDENTITY (1, 1) NOT NULL,
    [DOCUMENTO]         BIGINT   NOT NULL,
    [DOCUMENTOPARCERIA] BIGINT   NOT NULL,
    [DATALEITURA]       DATETIME NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ACESSOSCLIENTE_CLIENTE] FOREIGN KEY ([DOCUMENTO]) REFERENCES [dbo].[CLIENTES] ([DOCUMENTO])
);

