CREATE TABLE [dbo].[CLIENTES] (
    [DOCUMENTO]       BIGINT        NOT NULL,
    [NOME]            VARCHAR (200) NULL,
    [DOCUMENTOORIGEM] BIGINT        NOT NULL,
    PRIMARY KEY CLUSTERED ([DOCUMENTO] ASC),
    CONSTRAINT [FK_CLIENTES_PARCERIA] FOREIGN KEY ([DOCUMENTOORIGEM]) REFERENCES [dbo].[PARCERIA] ([DOCUMENTO])
);

