CREATE TABLE [dbo].[PARCERIA] (
    [DOCUMENTO]      BIGINT        NOT NULL,
    [NOME]           VARCHAR (200) NOT NULL,
    [URLAPICONSULTA] VARCHAR (200) NULL,
    PRIMARY KEY CLUSTERED ([DOCUMENTO] ASC)
);

